### ISSUE TITLE
Can't build from checkout

### ISSUE THREAD

**Issue by bpappin** [googlei18n/libaddressinput#100]
Looks like there is a class format error int he build somewhere.
This can likely be fixed by specifying the java version to build with.

This is my entire output:

`
cx2s-bpappin:libaddressinput bpappin$ gradle clean install
WARNING: Dependency org.json:json:20090211 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
WARNING: Dependency org.json:json:20090211 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
WARNING: Dependency org.json:json:20090211 is ignored for debugUnitTest as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
WARNING: Dependency org.json:json:20090211 is ignored for releaseUnitTest as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
WARNING: Dependency org.json:json:20090211 is ignored for debugAndroidTest as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
:android:clean
:common:clean
:android:preBuild UP-TO-DATE
:android:preDebugAndroidTestBuild UP-TO-DATE
[... removed cruft for clarity ...]
:android:bundleDebug
:android:assembleDebug
:android:processDebugAndroidTestManifest
:android:compileDebugAndroidTestRenderscript
:android:generateDebugAndroidTestBuildConfig
:android:generateDebugAndroidTestAssets UP-TO-DATE
:android:mergeDebugAndroidTestAssets
:android:generateDebugAndroidTestResValues UP-TO-DATE
:android:generateDebugAndroidTestResources
:android:mergeDebugAndroidTestResources
:android:processDebugAndroidTestResources
:android:generateDebugAndroidTestSources
:android:compileDebugAndroidTestJava
:android:preDexDebugAndroidTest
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/google/i18n/addressinput/common/AddressData$1.class
1 error; aborting

:android:preDexDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:preDexDebugAndroidTest'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.979 secs

`

**Comment by bpappin** [comment]
To fix locally, i added:

common/
```
apply plugin: 'java'

sourceCompatibility = 1.7
targetCompatibility = 1.7
```

an in android/
```
android {
    ....
    compileOptions{
	    sourceCompatibility=JavaVersion.VERSION_1_7
	    targetCompatibility=JavaVersion.VERSION_1_7
	}
}
```

**Comment by rsolomakhin** [comment]
Does not repro with "gradle clean build", but repros with "gradle clean install". Will try your fix and send a PR if it works.

**Comment by rsolomakhin** [comment]
Only changes in `common/` are required. Changes in `android/` are not necessary. @bpappin Can you verify this in your build?

**Comment by rsolomakhin** [comment]
https://github.com/googlei18n/libaddressinput/pull/102

**Comment by bpappin** [comment]
I can't, I'm not using the library as I could not getting it working easily and had to move on.
I intend to come back to it, but until then it will have to wait.

**Comment by rsolomakhin** [comment]
Thank you for the response, @bpappin
